"use client";
import { useState } from "react";
import { EventCard } from "./event-card";
import { usePlatform } from "@/components/platform/provider";
import { Badge, Empty, Field } from "@/components/platform/ui";
import { lifecycleLabels } from "@/lib/platform-model";
export function EventsBrowser(){
 const {state}=usePlatform();const [query,setQuery]=useState("");const [lifecycle,setLifecycle]=useState("all");const [category,setCategory]=useState("");const [type,setType]=useState("");const [program,setProgram]=useState("");const [price,setPrice]=useState("");const [cert,setCert]=useState("");const [date,setDate]=useState("");const [city,setCity]=useState("");
 const events=state.events.filter(e=>e.publication==="published");
 const filtered=events.filter(e=>(lifecycle==="all"||e.lifecycle===lifecycle)&&(!query||[e.title,e.category,e.speaker,e.venue].join(" ").toLowerCase().includes(query.toLowerCase()))&&(!category||e.category===category)&&(!type||e.type===type)&&(!program||e.programType===program)&&(!date||e.startAt.slice(0,10)===date)&&(!city||e.city===city)&&(!price||(price==="free"?e.price===0:price==="low"?e.price<=200000:e.price>200000))&&(!cert||(cert==="credit"?e.credits>0:e.tickets.some(t=>t.benefits.some(b=>/sertifikat|certificate/i.test(b))))));
 function reset(){setQuery("");setLifecycle("all");setCategory("");setType("");setProgram("");setPrice("");setCert("");setDate("");setCity("");}
 return <div><div className="flow-tabs" aria-label="Status event">{[["all","Semua"],...Object.entries(lifecycleLabels)].map(([value,label])=><button key={value} aria-pressed={lifecycle===value} onClick={()=>setLifecycle(value)}>{label}</button>)}</div><div className="mb-10 border-y border-content-title/15 py-6"><div className="grid gap-5 md:grid-cols-3"><Field label="Cari event"><input type="search" placeholder="Judul, topik, atau pembicara" value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Kategori"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Semua kategori</option>{Array.from(new Set(events.map(e=>e.category))).map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Format kehadiran"><select value={type} onChange={e=>setType(e.target.value)}><option value="">Semua format</option><option value="ONLINE">Online</option><option value="ONSITE">Offline / onsite</option><option value="HYBRID">Hybrid</option></select></Field></div><details className="mt-5"><summary className="min-h-11 cursor-pointer content-center text-sm font-semibold text-primary-600">Filter lainnya</summary><div className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-5"><Field label="Jenis event"><select value={program} onChange={e=>setProgram(e.target.value)}><option value="">Semua jenis</option>{Array.from(new Set(events.map(e=>e.programType))).map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Tanggal"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Harga"><select value={price} onChange={e=>setPrice(e.target.value)}><option value="">Semua harga</option><option value="free">Gratis</option><option value="low">Sampai Rp200.000</option><option value="high">Di atas Rp200.000</option></select></Field><Field label="Sertifikasi"><select value={cert} onChange={e=>setCert(e.target.value)}><option value="">Semua</option><option value="certificate">Dengan sertifikat</option><option value="credit">Dengan kredit SKP</option></select></Field><Field label="Kota"><select value={city} onChange={e=>setCity(e.target.value)}><option value="">Semua kota</option>{Array.from(new Set(events.map(e=>e.city))).map(v=><option key={v}>{v}</option>)}</select></Field></div></details><div className="mt-5 flex items-center justify-between border-t pt-4"><p className="text-xs text-content-muted" aria-live="polite">Menampilkan {filtered.length} dari {events.length} event</p><button className="min-h-11 px-3 text-sm font-semibold text-primary-600" onClick={reset}>Reset filter</button></div></div>{filtered.length?filtered.map((e,i)=><div key={e.slug}><Badge>{lifecycleLabels[e.lifecycle]} · {e.programType}</Badge><EventCard event={e} index={i}/></div>):<Empty title="Belum ada event yang cocok" description="Ubah kata kunci atau reset filter untuk melihat pilihan lain."/>}</div>;
}
