export const companyProfile = {
  name: "Awan Event",
  legalEntity: "PT Awan Berkah Bermartabat",
  field: "Pendidikan dan Pelatihan Kesehatan",
  tagline: "Meningkatkan Kompetensi Tenaga Kesehatan untuk Pelayanan Berkualitas",
  overview: [
    "Awan Event adalah organisasi pendidikan dan pelatihan kesehatan yang menjadi wadah profesional untuk meningkatkan pengetahuan, keterampilan, dan kompetensi di bidang kesehatan.",
    "Setiap program dirancang secara terencana, terukur, aplikatif, dan berorientasi pada mutu. Kegiatan dapat diselenggarakan secara tatap muka, daring, maupun hybrid sesuai kebutuhan peserta dan mitra.",
  ],
  vision: "Menjadi organisasi pendidikan dan pelatihan kesehatan yang profesional, inovatif, terpercaya, dan berkelanjutan dalam meningkatkan kompetensi sumber daya manusia kesehatan.",
  missions: [
    "Menyelenggarakan program pendidikan dan pelatihan kesehatan yang bermutu, relevan, dan sesuai kebutuhan.",
    "Menghadirkan narasumber, trainer, dan fasilitator sesuai kompetensi dan bidang keilmuan.",
    "Mengembangkan metode pembelajaran interaktif, praktis, dan berorientasi pada penerapan.",
    "Membangun jejaring dengan fasilitas kesehatan, institusi pendidikan, organisasi profesi, pemerintah, swasta, dan mitra strategis.",
    "Memanfaatkan teknologi digital untuk memperluas akses pendidikan dan informasi kesehatan.",
    "Melaksanakan evaluasi dan perbaikan berkelanjutan terhadap program dan pelayanan kegiatan.",
    "Mendorong budaya belajar sepanjang hayat bagi tenaga kesehatan.",
  ],
  values: [
    { title: "Profesionalisme", description: "Bekerja berdasarkan kompetensi, standar, etika, dan tanggung jawab." },
    { title: "Integritas", description: "Menjaga kejujuran, transparansi, akuntabilitas, dan komitmen." },
    { title: "Kolaborasi", description: "Membangun kerja sama antara peserta, trainer, institusi, dan jejaring profesional." },
    { title: "Inovasi", description: "Mengembangkan program, media, dan metode belajar sesuai perkembangan." },
    { title: "Mutu", description: "Melakukan perencanaan, evaluasi, dan perbaikan secara berkelanjutan." },
    { title: "Responsif", description: "Menyesuaikan program dengan kebutuhan peserta dan mitra." },
  ],
  team: [
    { name: "dr. Eka Nasrur Maulana, SpOG", role: "Pembina / Penasehat" },
    { name: "Anik Prabawaningsih Basuki, STr.Keb", role: "Ketua / Direktur Awan Event" },
    { name: "Karina Pradipta, S.Psi", role: "Sekretaris" },
    { name: "Nabila Rizkyta Putri Awan", role: "Bendahara" },
    { name: "Firda Atika, SKM", role: "Kerja Sama, Jejaring, Humas, dan Marketing" },
    { name: "Bagus Stiyo Budi, S.Kom", role: "IT dan Media Digital" },
  ],
  services: [
    { title: "Pelatihan Kesehatan", description: "Program terstruktur untuk meningkatkan pengetahuan dan keterampilan." },
    { title: "Workshop", description: "Pembelajaran intensif melalui diskusi, studi kasus, dan praktik." },
    { title: "Seminar", description: "Forum ilmiah untuk berbagi pengetahuan, pengalaman, dan perkembangan terbaru." },
    { title: "Webinar", description: "Edukasi daring bersama narasumber kompeten dengan jangkauan peserta lebih luas." },
    { title: "Bimbingan Teknis", description: "Pendampingan teknis yang disesuaikan dengan kebutuhan institusi atau mitra." },
    { title: "In House Training", description: "Program khusus yang dirancang berdasarkan kebutuhan organisasi atau fasilitas kesehatan." },
    { title: "Konsultasi dan Pengembangan", description: "Pendampingan penyusunan program edukasi, materi, dan pengembangan kompetensi." },
    { title: "Event Kesehatan", description: "Penyelenggaraan kegiatan edukatif sekaligus pengembangan jejaring kesehatan." },
  ],
  topics: [
    "Basic Trauma and Cardiac Life Support",
    "Basic Life Support",
    "Resusitasi Neonatus",
    "Pelatihan PONED",
    "Manajemen Ambulans Prehospital",
    "Code Blue dan Rapid Response System",
    "Early Warning System",
    "Patient Safety",
    "Komunikasi Efektif SBAR",
    "Dokumentasi Keperawatan dan Kebidanan",
    "Audit Klinis dan Mutu Pelayanan",
    "Konseling Menyusui",
    "Kegawatdaruratan Maternal dan Neonatal",
    "Peningkatan Mutu dan Keselamatan Pelayanan",
  ],
  methods: [
    "Presentasi dan pemaparan materi",
    "Diskusi interaktif",
    "Studi kasus",
    "Demonstrasi",
    "Praktik dan simulasi",
    "Tanya jawab dan refleksi pembelajaran",
    "Pre-test dan post-test sesuai kebutuhan",
    "Evaluasi kepuasan peserta",
    "Pembelajaran tatap muka, daring, dan hybrid",
  ],
  process: [
    { title: "Identifikasi kebutuhan", description: "Menentukan sasaran, kebutuhan kompetensi, tema, dan tujuan." },
    { title: "Penyusunan program", description: "Menyusun materi, metode, narasumber, jadwal, dan rencana kegiatan." },
    { title: "Persiapan administrasi", description: "Menyiapkan pendaftaran, presensi, materi, sertifikat, dan kebutuhan teknis." },
    { title: "Publikasi dan promosi", description: "Menyiapkan flyer, konten digital, undangan, dan komunikasi peserta." },
    { title: "Pelaksanaan", description: "Menjalankan kegiatan berdasarkan rundown dan standar teknis." },
    { title: "Evaluasi", description: "Mengukur proses, respons peserta, hasil belajar, dan kendala kegiatan." },
    { title: "Pelaporan", description: "Menyusun dokumentasi serta laporan kegiatan secara tertib." },
    { title: "Tindak lanjut", description: "Menindaklanjuti hasil evaluasi dan peluang pengembangan program." },
  ],
  audiences: [
    "Perawat",
    "Bidan",
    "Dokter dan tenaga medis",
    "Tenaga kesehatan lainnya",
    "Mahasiswa bidang kesehatan",
    "Institusi pelayanan kesehatan",
    "Institusi pendidikan kesehatan",
    "Organisasi, komunitas, dan mitra",
  ],
  partnerships: [
    "Pelatihan bersama",
    "Webinar atau seminar bersama",
    "In house training",
    "Pengembangan program dan materi edukasi",
    "Penyediaan narasumber, trainer, atau fasilitator",
    "Pengembangan jejaring dan kegiatan kesehatan",
  ],
  contacts: {
    instagram: "awan_event",
    youtube: "@awanevent",
    email: "awanevents24@gmail.com",
    phone: "085815087774",
  },
} as const;
