"use client";
import { useState, type FormEvent } from "react";
import { Field, Panel } from "@/components/platform/ui";
export function LeadForm({kind,eventSlug}:{kind:"program"|"contact"|"waitlist";eventSlug?:string}){
 const [sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch("/api/inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,kind,eventSlug})});const result=await r.json();if(!r.ok)throw new Error(result.error?.message||"Pesan belum terkirim. Coba lagi.");setSent(true);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(sent)return <Panel><h2 className="text-xl font-semibold" role="status">{kind==="waitlist"?"Anda masuk daftar tunggu":"Pesan terkirim"}</h2><p className="mt-3 text-sm">{kind==="waitlist"?"Tim akan menghubungi Anda jika kursi tersedia.":"Tim akan menghubungi Anda melalui kontak yang diberikan."}</p></Panel>;
 return <Panel><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field label="Nama lengkap"><input name="name" required maxLength={160} autoComplete="name"/></Field><Field label="Email"><input name="email" required type="email" autoComplete="email"/></Field><Field label="WhatsApp"><input name="phone" required type="tel" maxLength={20} autoComplete="tel"/></Field><Field label="Institusi"><input name="institution" maxLength={160}/></Field><Field label={kind==="waitlist"?"Tiket yang diminati":"Pesan"} className="sm:col-span-2"><textarea name="message" required rows={5} maxLength={3000}/></Field><label className="hidden" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="flex gap-3 text-sm sm:col-span-2"><input type="checkbox" required/>Saya bersedia dihubungi terkait permintaan ini.</label>{error&&<p role="alert" className="flow-alert danger sm:col-span-2">{error}</p>}<button disabled={busy} className="flow-button sm:col-span-2">{busy?"Mengirim…":kind==="waitlist"?"Masuk daftar tunggu":"Kirim pesan"}</button></form></Panel>;
}
